name: Auto-merge Sync PRs

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Auto-merge labeled Yandex sync PRs older than 25 minutes
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          # Cutoff timestamp for 25 minutes ago (UTC)
          CUTOFF=$(date -u -d '25 minutes ago' +%s)
          echo "Cutoff (UTC seconds): $CUTOFF"

          # List candidate PRs: labeled, open, base main, head sync/yadisk, mergeable
          gh pr list \
            --search 'label:"sync:auto-merge" is:open base:main head:sync/yadisk' \
            --json number,mergeable,createdAt \
            --jq '.[] | select(.mergeable=="MERGEABLE") | {number, createdAt: (.createdAt|fromdate)}' \
            -R "$GITHUB_REPOSITORY" | \
          jq -c '. | select(.createdAt <= env.CUTOFF)' | \
          while read -r item; do
            pr=$(echo "$item" | jq -r '.number')
            echo "Merging PR #$pr (squash) ..."
            gh pr merge "$pr" --squash --delete-branch --yes -R "$GITHUB_REPOSITORY"
          done

