name: CI Tests

on:
  push:
  pull_request:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  bun-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
      - name: Install dependencies
        run: bun install
      - name: Guard: no .only/.skip in tests
        shell: bash
        run: |
          if [ -d tests ] && grep -RInE '^\s*(it|describe|test)\.(only|skip)\s*\(' tests; then
            echo 'Error: .only/.skip found in tests' >&2
            exit 1
          fi
      - name: Type check
        run: bun run typecheck
      - name: Run tests
        run: bun test --coverage
