name: CI Tests

on:
  push:
  pull_request:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  deno-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.5.4
      - name: "Guard: no .only/.skip in tests"
        shell: bash
        run: |
          if [ -d tests ] && grep -RInE '^\s*(it|describe|test)\.(only|skip)\s*\(' tests; then
            echo 'Error: .only/.skip found in tests' >&2
            exit 1
          fi
      - name: Lint
        run: deno lint
      - name: Type check
        run: deno check scripts/**/*.ts tests/**/*.ts
      - name: Run tests
        run: deno test -A
