name: "Industry Research (Daily)"
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch: {}
  pull_request: {}

permissions:
  contents: read
  actions: read
  checks: read
  statuses: read

concurrency:
  group: industry-research-daily

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: read
      statuses: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1
        with:
          bun-version: '1.2.3'

      - name: Install deps for research script
        run: |
          bun add @google/generative-ai@latest

      - name: Generate daily industry research report (TS + Gemini)
        env:
          GOOGLE_AI_API_KEY: ${{ secrets.GOOGLE_AI_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bun scripts/agentic/industry-research.ts

      - name: Copy job summary for artifact (optional)
        if: always()
        run: |
          if [ -n "${GITHUB_STEP_SUMMARY}" ] && [ -f "${GITHUB_STEP_SUMMARY}" ]; then
            cp "$GITHUB_STEP_SUMMARY" /tmp/industry-research-summary.md
          else
            echo "No step summary file found" > /tmp/industry-research-summary.md
          fi

      - name: Upload step summary as artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: industry-research-summary
          path: /tmp/industry-research-summary.md
          if-no-files-found: warn

