name: "Industry Research (Daily)"
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch: {}
  pull_request:
    paths:
      - 'yadisk/First Principles Framework — Core Conceptual Specification (holonic).md'

permissions:
  contents: read
  actions: read
  checks: read
  statuses: read

concurrency:
  group: industry-research-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      actions: read
      checks: read
      statuses: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.5.4

      - name: Generate daily industry research report (TS + Gemini)
        env:
          GOOGLE_AI_API_KEY: ${{ secrets.GOOGLE_AI_API_KEY }}
          GEMINI_MODEL: gemini-2.5-pro
          USE_SEARCH_GROUNDING: "false"
          # Optional: include small FPF headings excerpt to ground context without extra API features
          # GROUND_FPF_EXCERPT_BYTES: "0"
          # GEN_TEMPERATURE: "0.3"
          # GEN_TOP_P: "0.9"
          # GEN_MAX_TOKENS: "2048"
        run: |
          deno run --allow-read --allow-env --allow-net --allow-write scripts/agentic/industry-research.ts
  
  summarize-fpf-changes:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.5.4

      - name: Summarize FPF changes
        env:
          GOOGLE_AI_API_KEY: ${{ secrets.GOOGLE_AI_API_KEY }}
          GEMINI_MODEL: gemini-2.5-pro
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          deno run --allow-read --allow-env --allow-net --allow-run scripts/agentic/summarize-fpf-changes.ts
