name: "Industry Research (Daily)"
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch: {}

permissions:
  contents: read
  actions: read
  checks: read
  statuses: read

concurrency:
  group: industry-research-daily

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: read
      statuses: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install google-generativeai requests

      - name: Generate daily industry research report (Gemini)
        env:
          GOOGLE_AI_API_KEY: ${{ secrets.GOOGLE_AI_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/industry_research.py

      - name: Upload step summary as artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: industry-research-summary
          path: ${{ env.GITHUB_STEP_SUMMARY }}
          if-no-files-found: warn

